---
- name: Ensure local path exists
  ansible.builtin.file:
    path: /tmp/app
    state: directory
  delegate_to: localhost
  become: false

- name: Clone app web respo
  ansible.builtin.git:
    repo: https://github.com/ByJeanCa/web-app-test.git
    dest: tmp/app
    version: main
  delegate_to: localhost