- name: Ensure remote temp path exists
  ansible.builtin.file:
    path: "{{ remote_temp_path }}"
    state: directory

- name: save pwd
  command: pwd
  register: actual_dir
  remote_src: yes

- name: debug
  debug:
    var: actual_dir

- name: Copy ZIP file to remote temp path
  ansible.builtin.copy:
    src: "{{ local_compressed_files }}/app.tar.gz"
    dest: "{{ remote_temp_path }}/app.tar.gz"
    remote_src: yes

- name: Unzip files on remote
  ansible.builtin.unarchive:
    src: "{{ remote_temp_path }}/app.tar.gz"
    dest: "{{ remote_temp_path }}/"

- name: Remove ZIP from remote
  ansible.builtin.file:
    path: "{{ remote_temp_path }}/app.tar.gz"
    state: absent

- name: Copy unzipped files to public path
  ansible.builtin.copy:
    src: "{{ remote_temp_path }}/"
    dest: "{{ server_path }}"

- name: Delete remote temp directory
  ansible.builtin.file:
    path: "{{ remote_temp_path }}"
    state: absent

- name: Ensure S3_BUCKET env variable is present in app service
  lineinfile:
    path: /etc/environment
    line: 'S3_BUCKET=s3-app-web-test1'
    create: yes
  notify: Restart flask app

- name: Check server response
  ansible.builtin.uri:
    url: "http://{{ ip }}"
    return_content: yes
  register: result
  failed_when: result.status != 200

- name: Show server response
  debug:
    msg: "{{ result.content }}"
