- name: Ensure remote temp path exists
  ansible.builtin.file:
    path: "{{ remote_temp_path }}"
    state: directory

- name: Copy ZIP file to remote temp path
  ansible.builtin.copy:
    src: "{{ local_compressed_files }}/app.zip"
    dest: "{{ remote_temp_path }}/app.zip"

- name: Unzip files on remote
  ansible.builtin.unarchive:
    src: "{{ remote_temp_path }}/app.zip"
    dest: "{{ remote_temp_path }}/"
    remote_src: yes

- name: Remove ZIP from remote
  ansible.builtin.file:
    path: "{{ remote_temp_path }}/app.zip"
    state: absent

- name: Copy unzipped files to public path
  ansible.builtin.copy:
    src: "{{ remote_temp_path }}/"
    dest: "{{ server_path }}"
    remote_src: yes

- name: Delete remote temp directory
  ansible.builtin.file:
    path: "{{ remote_temp_path }}"
    state: absent

- name: Ensure S3_BUCKET env variable is present in app service
  lineinfile:
    path: /etc/environment
    line: 'S3_BUCKET=s3-app-web-test1'
    create: yes
  notify: Restart flask app

- name: Check server response
  ansible.builtin.uri:
    url: "http://{{ ip }}"
    return_content: yes
  register: result
  failed_when: result.status != 200

- name: Show server response
  debug:
    msg: "{{ result.content }}"
