services:
  s3-app-test:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    networks:
      - jenkins-net
    env_file:
      - .env                        
    command: ["pytest", "test_app.py"] 

networks:
  jenkins-net:
    external: true
