---
- name: Running tests
  hosts: tests servers
  vars:
  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

    - name: Compressing files
      ansible.builtin.archive:
        path: "{{ local_files }}/*"
        dest: "{{ local_compressed_files }}/file_{{ current_date }}.zip"
        format: .zip
      register: compress_result
      delegate_to: localhost
      failed_when: compress_result.failed is defined and compress_result.failed

    - name: Ensurance remote temporal path exits
      ansible.builtin.file:
        path: "{{ remote_temp_path }}"
        state: directory

    - name: Copy files to temp path into the server
      ansible.builtin.copy:
        src: "{{ local_compressed_files }}/file_{{ current_date }}.zip"
        dest: "{{ remote_temp_path }}/file_{{ current_date }}.zip"

    - name: Unzip files
      ansible.builtin.unarchive:
        src: "{{ remote_temp_path }}/file_{{ current_date }}.zip"
        dest: "{{ remote_temp_path }}/"

    - name: Delete zip file
      ansible.builtin.file:
        path: "{{ remote_temp_path }}/file_{{ current_date }}.zip"
        state: absent

    - name: Copy files on the public path server
      ansible.builtin.copy:
        src: "{{ remote_temp_path }}/"
        dest: ""
    